### ISSUE TITLE
notification does not appear

### ISSUE THREAD

**Issue by DemetAkyol** [kadircanerergun/laravel-onesignal#5]
In this case the notification does not appear when I run. Just opening a blank page

**Comment by kadircanerergun** [comment]
can you describe the case ?

**Comment by DemetAkyol** [comment]
I made my onesignal settings, the empty screen opens when I follow your Installation and usage steps.
forr example my route;
Route::get('/notify', 'Auth\NotificationControllerController@pushN')->name('notify');
 public function pushN(){
        try{        \KCE\OneSignal\Facades\OneSignalClient::sendToAll('Notification message');
        return View('push');
        }catch (\Exception $exception)
        {
            dd($exception->getMessage());
        }
    }

**Comment by kadircanerergun** [comment]
What includes the view push ? Is it blank ? And could you check your clients that they could get notifications?

**Comment by DemetAkyol** [comment]
in push view;
<head><link rel="manifest" href="/manifest.json" />
    <head>
        <link rel="manifest" href="/manifest.json" />
        <script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async=""></script>
        <script>
            var OneSignal = window.OneSignal || [];
            OneSignal.push(function() {
                OneSignal.init({
                    appId: "2307f437-38d7-4c0b-806a-e7b55fcfcbdd",
                    autoRegister: false,
                    notifyButton: {
                        enable: true,
                    },
                });
                OneSignal.registerForPushNotifications();
            });
        </script>
    </head>

and I'm working on localhost.

**Comment by kadircanerergun** [comment]
I think there is a misunderstood here. The page that you send should show before trying to send push notification and client should subscribed. This library not for showing notification. to make sending notification easier with laravel and onesignal.

**Comment by DemetAkyol** [comment]
I understand, is this your source can be used for both web and mobile?

**Comment by kadircanerergun** [comment]
yes you can use for  both
